import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Headers from "@/components/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Creative single page site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-commissioner max-w-[1440px] mx-auto min-h-screen bg-white lg:pl-40 md:pl-10 pl-4`}
      >
        <Headers />
        {children}
      </body>
    </html>
  );
}
