import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Container from "@/components/container";
import Headers from "@/components/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const commissioner = localFont({
  src: [
    { path: "./fonts/static/Commissioner-ExtraBold.ttf", weight: "800" },
    { path: "./fonts/static/Commissioner-Bold.ttf", weight: "700" },
    { path: "./fonts/static/Commissioner-Medium.ttf", weight: "500" },
    { path: "./fonts/static/Commissioner-Regular.ttf", weight: "400" },
    { path: "./fonts/static/Commissioner-Light.ttf", weight: "300" },
  ],
  variable: "--font-commissioner",
});

export const metadata: Metadata = {
  title: "Creative single page site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${commissioner.variable} ${geistSans.variable} ${geistMono.variable} antialiased bg-gray-500`}
      >
        <Container>
          <Headers />
          {children}
        </Container>
      </body>
    </html>
  );
}
